/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extonextgroup.extonext_v2;

import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author DELL
 */
public class BuyScreen extends javax.swing.JFrame {

     public static String user;
    public static int page = 4;
    public static int previous;
    ArrayList<String> itemlist;
    DBConnector db = new DBConnector();
    String category;
    FilteredBuyScreen filteredBuy = new FilteredBuyScreen();
    /**
     * Creates new form BuyScreen
     */
    public BuyScreen() {
        initComponents();
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        profilemenu = new javax.swing.JMenuItem();
        logoutmenu = new javax.swing.JMenuItem();
        background1 = new netbeanscomponents.background();
        jPanel1 = new javax.swing.JPanel();
        vehicleoption = new javax.swing.JRadioButton();
        clothesoption = new javax.swing.JRadioButton();
        furnitureoption = new javax.swing.JRadioButton();
        bookoption = new javax.swing.JRadioButton();
        electronicoption = new javax.swing.JRadioButton();
        searchbar = new javax.swing.JTextField();
        exchangeoption = new javax.swing.JRadioButton();
        saleoption = new javax.swing.JRadioButton();
        backbutton = new javax.swing.JButton();
        logobutton = new javax.swing.JButton();
        additembutton = new javax.swing.JButton();
        messagebutton = new javax.swing.JButton();
        profilebutton = new javax.swing.JButton();
        sendbutton = new javax.swing.JButton();

        jPopupMenu1.setBackground(new java.awt.Color(204, 0, 255));
        jPopupMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jPopupMenu1.setAlignmentX(10.0F);

        profilemenu.setBackground(new java.awt.Color(204, 0, 255));
        profilemenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        profilemenu.setForeground(new java.awt.Color(255, 255, 255));
        profilemenu.setText("Go Profile");
        profilemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilemenuMouseClicked(evt);
            }
        });
        profilemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilemenuActionPerformed(evt);
            }
        });
        jPopupMenu1.add(profilemenu);

        logoutmenu.setBackground(new java.awt.Color(204, 0, 255));
        logoutmenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logoutmenu.setForeground(new java.awt.Color(255, 255, 255));
        logoutmenu.setText("Logout");
        logoutmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutmenuActionPerformed(evt);
            }
        });
        jPopupMenu1.add(logoutmenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 5, 0, 50));

        vehicleoption.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroup1.add(vehicleoption);
        vehicleoption.setForeground(new java.awt.Color(153, 51, 255));
        vehicleoption.setText("Vehicle");
        vehicleoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleoptionActionPerformed(evt);
            }
        });
        jPanel1.add(vehicleoption);

        clothesoption.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroup1.add(clothesoption);
        clothesoption.setForeground(new java.awt.Color(153, 51, 255));
        clothesoption.setText("Clothes");
        clothesoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothesoptionActionPerformed(evt);
            }
        });
        jPanel1.add(clothesoption);

        furnitureoption.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroup1.add(furnitureoption);
        furnitureoption.setForeground(new java.awt.Color(153, 51, 255));
        furnitureoption.setText("Furniture");
        furnitureoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                furnitureoptionActionPerformed(evt);
            }
        });
        jPanel1.add(furnitureoption);

        bookoption.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroup1.add(bookoption);
        bookoption.setForeground(new java.awt.Color(153, 51, 255));
        bookoption.setText("Book");
        bookoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookoptionActionPerformed(evt);
            }
        });
        jPanel1.add(bookoption);

        electronicoption.setBackground(new java.awt.Color(255, 255, 153));
        buttonGroup1.add(electronicoption);
        electronicoption.setForeground(new java.awt.Color(153, 51, 255));
        electronicoption.setText("Electronic Devices");
        electronicoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electronicoptionActionPerformed(evt);
            }
        });
        jPanel1.add(electronicoption);

        searchbar.setText("Search..");
        searchbar.setOpaque(false);
        searchbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbarMouseClicked(evt);
            }
        });
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });

        exchangeoption.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(exchangeoption);
        exchangeoption.setSelected(true);
        exchangeoption.setText("Exchange");
        exchangeoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangeoptionActionPerformed(evt);
            }
        });

        saleoption.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(saleoption);
        saleoption.setText("Sell");
        saleoption.setOpaque(false);
        saleoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleoptionActionPerformed(evt);
            }
        });

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/backbutton.png"))); // NOI18N
        backbutton.setBorder(null);
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        logobutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/logo.png"))); // NOI18N
        logobutton.setBorder(null);
        logobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logobuttonActionPerformed(evt);
            }
        });

        additembutton.setBackground(new java.awt.Color(255, 255, 255));
        additembutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/37x37uploadbutton.png"))); // NOI18N
        additembutton.setBorder(null);
        additembutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additembuttonActionPerformed(evt);
            }
        });

        messagebutton.setBackground(new java.awt.Color(255, 255, 255));
        messagebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/55x37messagebutton.png"))); // NOI18N
        messagebutton.setBorder(null);
        messagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagebuttonActionPerformed(evt);
            }
        });

        profilebutton.setBackground(new java.awt.Color(255, 255, 255));
        profilebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/37x37profilebutton.png"))); // NOI18N
        profilebutton.setBorder(null);
        profilebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebuttonActionPerformed(evt);
            }
        });

        sendbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/babacım.png"))); // NOI18N
        sendbutton.setBorder(null);
        sendbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchbar)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE))
                .addGap(142, 142, 142))
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(exchangeoption)
                        .addGap(323, 323, 323)
                        .addComponent(saleoption))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(logobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(535, 535, 535)
                        .addComponent(additembutton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(messagebutton)
                        .addGap(0, 0, 0)
                        .addComponent(profilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(511, 511, 511)
                        .addComponent(sendbutton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(backbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(additembutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exchangeoption)
                    .addComponent(saleoption))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(sendbutton)
                .addGap(150, 150, 150))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.hide();
        openPage(previous);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void profilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebuttonActionPerformed
        // TODO add your handling code here:
        jPopupMenu1.show(this,989,117);
    }//GEN-LAST:event_profilebuttonActionPerformed

    private void profilemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilemenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profilemenuMouseClicked

    private void profilemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilemenuActionPerformed
        // TODO add your handling code here:
        this.hide();
        PersonalProfilePage personalProfile = new PersonalProfilePage();
        personalProfile.setPage(page);
        personalProfile.setUser(user);
        personalProfile.paintPage();
        personalProfile.setVisible(true);
        
    }//GEN-LAST:event_profilemenuActionPerformed

    private void logoutmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutmenuActionPerformed
        // TODO add your handling code here:
        infoBox("Successfully logged out" , "logout" );
        this.hide();
        LoginScreen login = new LoginScreen();
        login.setVisible(true);
    }//GEN-LAST:event_logoutmenuActionPerformed

    private void additembuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additembuttonActionPerformed
        // TODO add your handling code here:
        this.hide();
        UploadScreen upload = new UploadScreen();
        upload.setVisible(true);
        upload.setPage(page);
        upload.setUser(user);
    }//GEN-LAST:event_additembuttonActionPerformed

    private void logobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logobuttonActionPerformed
        // TODO add your handling code here:
        this.hide();
        MainPagePersonal personal = new MainPagePersonal();
        personal.setVisible(true);
        personal.setPage(page);
        personal.setUser(user);
    }//GEN-LAST:event_logobuttonActionPerformed

    private void messagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagebuttonActionPerformed
        // TODO add your handling code here:
        this.hide();
        MessagePage message = new MessagePage();
        message.setVisible(true);
        message.setPage(page);
        message.setUser(user);
    }//GEN-LAST:event_messagebuttonActionPerformed

    private void saleoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleoptionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_saleoptionActionPerformed

    private void sendbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbuttonActionPerformed
        // TODO add your handling code here:
       
        if(saleoption.isSelected()){
        if(vehicleoption.isSelected() && saleoption.isSelected()) {
            try{
            itemlist = db.sellListBuySearchCat(searchbar.getText(),"Vehicle");
            }catch(Exception e)
            {
                e.getMessage();
            }
        }
        else if(clothesoption.isSelected() && saleoption.isSelected()) {
            try{
            itemlist = db.sellListBuySearchCat(searchbar.getText(),"Clothes");
            }catch(Exception e)
            {
                e.getMessage();
            }
        }
        else if(furnitureoption.isSelected() && saleoption.isSelected()) {
            try{
            itemlist = db.sellListBuySearchCat(searchbar.getText(),"Furniture");
            }catch(Exception e)
            {
                e.getMessage();
            }
        }
        else if(bookoption.isSelected() && saleoption.isSelected()) {
            try{
            itemlist = db.sellListBuySearchCat(searchbar.getText(),"Book");
            }catch(Exception e)
            {
                e.getMessage();
            }
        }
        else if(electronicoption.isSelected() && saleoption.isSelected()) {
            try{
            itemlist = db.sellListBuySearchCat(searchbar.getText(),"Electronics");
            }catch(Exception e)
            {
                e.getMessage();
            }
        }
        else {
            try{
            itemlist = db.sellListBuySearch(searchbar.getText());
            }catch(Exception e)
            {
                e.getMessage();
            }
        }
        this.hide();
                
        filteredBuy.setSale(true);
        filteredBuy.setList(itemlist);
        filteredBuy.setUser(user);
        filteredBuy.setPage(page);
        filteredBuy.paintPage();
        filteredBuy.setVisible(true);
        }
        
        
        
        //**************************************************************
        
        else {
            if(vehicleoption.isSelected() && exchangeoption.isSelected()) {
            try{
                
            itemlist = db.exchangeListBuySearchCat(searchbar.getText(),"Vehicle");
            }catch(Exception e)
            {
                e.getMessage();
            }
        }
        else if(clothesoption.isSelected() && exchangeoption.isSelected()) {
            try{
            itemlist = db.exchangeListBuySearchCat(searchbar.getText(),"Clothes");
            }catch(Exception e)
            {
                e.getMessage();
            }
        }
        else if(furnitureoption.isSelected() && exchangeoption.isSelected()) {
            try{
            itemlist = db.exchangeListBuySearchCat(searchbar.getText(),"Furniture");
            }catch(Exception e)
            {
                e.getMessage();
            }
        }
        else if(bookoption.isSelected() && exchangeoption.isSelected()) {
            try{
            itemlist = db.exchangeListBuySearchCat(searchbar.getText(),"Books");
            }catch(Exception e)
            {
                e.getMessage();
            }
        }
        else if(electronicoption.isSelected() && exchangeoption.isSelected()) {
            try{
            itemlist = db.exchangeListBuySearchCat(searchbar.getText(),"Electronics");
            }catch(Exception e)
            {
                e.getMessage();
            }
        }
        else {
            try{
                
            itemlist = db.exchangeListBuySearch(searchbar.getText());
            }catch(Exception e)
            {
                e.getMessage();
            }
        }
        
        
        
            
        //************************************************ 
        System.out.println(itemlist.toString());
        this.hide();
        
        filteredBuy.setSale(false);
        filteredBuy.setList(itemlist);
        filteredBuy.setUser(user);
        filteredBuy.setPage(page);
        filteredBuy.paintPage();
        
        filteredBuy.setVisible(true);
        }
    }//GEN-LAST:event_sendbuttonActionPerformed

    private void bookoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookoptionActionPerformed
        // TODO add your handling code here:
        category = "movie/book";
    }//GEN-LAST:event_bookoptionActionPerformed

    private void furnitureoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_furnitureoptionActionPerformed
        // TODO add your handling code here:
        category = "furniture";
    }//GEN-LAST:event_furnitureoptionActionPerformed

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchbarActionPerformed

    private void exchangeoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangeoptionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_exchangeoptionActionPerformed

    private void vehicleoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleoptionActionPerformed
        // TODO add your handling code here:
        category = "Vehicle";
    }//GEN-LAST:event_vehicleoptionActionPerformed

    private void clothesoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothesoptionActionPerformed
        // TODO add your handling code here:
        category = "clothes";
    }//GEN-LAST:event_clothesoptionActionPerformed

    private void electronicoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electronicoptionActionPerformed
        // TODO add your handling code here:
        category = "electronic";
    }//GEN-LAST:event_electronicoptionActionPerformed

    private void searchbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbarMouseClicked
        // TODO add your handling code here:
        searchbar.setText("");
    }//GEN-LAST:event_searchbarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyScreen().setVisible(true);
            }
        });
    }
    
    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "" + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
     public static void setUser(String username){
        user = username;
    }
    public static void setPage(int pagenum){
        previous = pagenum;
    }
    
    public void openPage(int pagenum){
        if (previous == 1) {
            AddDonationListPage donaListPage = new AddDonationListPage();
            donaListPage.setVisible(true);
            donaListPage.setUser(user);
            
        }
        if (previous == 2) {
            AfterDonationPage donaPage = new AfterDonationPage();
            
            donaPage.setUser(user);
            donaPage.paintPage();
            donaPage.setVisible(true);
        }
        if (previous == 3) {
            AfterDonationScreenCorp donaScreenCorp = new AfterDonationScreenCorp();
            donaScreenCorp.setVisible(true);
            donaScreenCorp.paintPage();
            donaScreenCorp.setUser(user);
        }
        if (previous == 4) {
            BuyScreen buyScreen = new BuyScreen();
           
            buyScreen.setUser(user);
             buyScreen.setVisible(true);
        }
        if (previous == 5) {
            CorpDonateScreen corpScreen = new CorpDonateScreen();
            
            corpScreen.setUser(user);
            corpScreen.setVisible(true);
        }
        if (previous == 6) {
            CorpProfilePage corpProfile = new CorpProfilePage();
            
            corpProfile.setUser(user);
            corpProfile.paintPage();
            corpProfile.setVisible(true);
        }
        if (previous == 7) {
            DonationFilteredsearchCorp fiteredCorp = new DonationFilteredsearchCorp();
            
            fiteredCorp.setUser(user);
            fiteredCorp.paintPage();
            fiteredCorp.setVisible(true);
        }
        if (previous == 8) {
            FilteredBuyScreen filteredBuy = new FilteredBuyScreen();
            
            filteredBuy.setUser(user);
            filteredBuy.paintPage();
            filteredBuy.setVisible(true);
        }
        if (previous == 9) {
            ItemDetailsPage itemDetails = new ItemDetailsPage();
            
            itemDetails.setUser(user);
            itemDetails.paintPage();
            itemDetails.setVisible(true);
        }
        if (previous == 10) {
            
        }
        if (previous == 11) {
            MainPageCorporation mainCorporation = new MainPageCorporation();
            mainCorporation.setVisible(true);
            mainCorporation.setUser(user);
        }
        if (previous == 12) {
            MainPagePersonal mainPersonal = new MainPagePersonal();
            mainPersonal.setVisible(true);
            mainPersonal.setUser(user);
        }
        if (previous == 13) {
            MessagePage messagePage = new MessagePage();
            
            messagePage.setUser(user);
            messagePage.paintPage();
            messagePage.setVisible(true);
        }
        if (previous == 14) {
            PersonalProfilePage personProfile = new PersonalProfilePage();
            
            personProfile.setUser(user);
            personProfile.paintPage();
            personProfile.setVisible(true);
        }
        if (previous == 15) {
        }

        if (previous == 16) {
            UploadScreen upload = new UploadScreen();
            upload.setVisible(true);
            upload.setUser(user);
        }
        if (previous == 17) {
            WishListListPage wishListList = new WishListListPage();
            wishListList.setVisible(true);
            wishListList.setUser(user);
        }
        if (previous == 18) {
            WishListPageCorp wishList = new WishListPageCorp();
            
            wishList.setUser(user);
            wishList.paintPage();
            wishList.setVisible(true);
        }
        if (previous == 19) {
            WishListPagePersonal wishListPersonal = new WishListPagePersonal();
           
            wishListPersonal.setUser(user);
            wishListPersonal.paintPage();
             wishListPersonal.setVisible(true);
        }
        if (previous == 20) {
            DonationPersonalPage donationPersonal = new DonationPersonalPage();
            donationPersonal.setVisible(true);
            donationPersonal.setUser(user);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additembutton;
    private javax.swing.JButton backbutton;
    private netbeanscomponents.background background1;
    private javax.swing.JRadioButton bookoption;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton clothesoption;
    private javax.swing.JRadioButton electronicoption;
    private javax.swing.JRadioButton exchangeoption;
    private javax.swing.JRadioButton furnitureoption;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton logobutton;
    private javax.swing.JMenuItem logoutmenu;
    private javax.swing.JButton messagebutton;
    private javax.swing.JButton profilebutton;
    private javax.swing.JMenuItem profilemenu;
    private javax.swing.JRadioButton saleoption;
    private javax.swing.JTextField searchbar;
    private javax.swing.JButton sendbutton;
    private javax.swing.JRadioButton vehicleoption;
    // End of variables declaration//GEN-END:variables
}
