/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extonextgroup.extonext_v2;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.io.File;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.io.IOException;
import static java.lang.Integer.parseInt;
/**
 *
 * @author DELL
 */
public class SignUpForm extends javax.swing.JFrame {

    public static String picurl;
    /**
     * Creates new form SignUpForm
     */
    public SignUpForm() {
        initComponents();
    }
    DBConnector db = new DBConnector();
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        signUpBackground1 = new netbeanscomponents.SignUpBackground();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        emailagain = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        passwordagain = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        browsefilebutton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        cardno = new javax.swing.JTextField();
        cardname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        duedate = new javax.swing.JTextField();
        cvc = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        phonenumber = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        city = new javax.swing.JTextField();
        province = new javax.swing.JTextField();
        signupbutton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        personaloption = new javax.swing.JRadioButton();
        corporationoption = new javax.swing.JRadioButton();
        backbutton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(6, 1, 0, 45));

        name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(204, 204, 204));
        name.setText("Name/CorpName:");
        name.setBorder(null);
        name.setOpaque(false);
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);

        username.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(204, 204, 204));
        username.setText("User Name:");
        username.setBorder(null);
        username.setOpaque(false);
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username);

        email.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setText("Email:");
        email.setBorder(null);
        email.setOpaque(false);
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email);

        emailagain.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        emailagain.setForeground(new java.awt.Color(204, 204, 204));
        emailagain.setText("Email Again:");
        emailagain.setBorder(null);
        emailagain.setOpaque(false);
        emailagain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailagainMouseClicked(evt);
            }
        });
        emailagain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailagainActionPerformed(evt);
            }
        });
        jPanel1.add(emailagain);

        password.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setText("Password:");
        password.setBorder(null);
        password.setOpaque(false);
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password);

        passwordagain.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        passwordagain.setForeground(new java.awt.Color(204, 204, 204));
        passwordagain.setText("Password Again:");
        passwordagain.setBorder(null);
        passwordagain.setOpaque(false);
        passwordagain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordagainMouseClicked(evt);
            }
        });
        jPanel1.add(passwordagain);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(6, 1, 0, 45));

        jPanel4.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Add Photo:");

        browsefilebutton.setBackground(new java.awt.Color(102, 102, 102));
        browsefilebutton.setForeground(new java.awt.Color(255, 255, 255));
        browsefilebutton.setText("Browse files");
        browsefilebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsefilebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(browsefilebutton)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(browsefilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setOpaque(false);

        cardno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cardno.setForeground(new java.awt.Color(204, 204, 204));
        cardno.setText("Card no:");
        cardno.setBorder(null);
        cardno.setOpaque(false);
        cardno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardnoMouseClicked(evt);
            }
        });

        cardname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cardname.setForeground(new java.awt.Color(204, 204, 204));
        cardname.setText("Name on the Card:");
        cardname.setBorder(null);
        cardname.setOpaque(false);
        cardname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardnameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardno, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(cardname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);

        duedate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        duedate.setForeground(new java.awt.Color(204, 204, 204));
        duedate.setText("Due Date:");
        duedate.setBorder(null);
        duedate.setOpaque(false);
        duedate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duedateMouseClicked(evt);
            }
        });
        duedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duedateActionPerformed(evt);
            }
        });

        cvc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cvc.setForeground(new java.awt.Color(204, 204, 204));
        cvc.setText("CVC:");
        cvc.setBorder(null);
        cvc.setOpaque(false);
        cvc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cvcMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(duedate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(cvc, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        address.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        address.setForeground(new java.awt.Color(204, 204, 204));
        address.setText("Address:");
        address.setBorder(null);
        address.setOpaque(false);
        address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressMouseClicked(evt);
            }
        });
        jPanel2.add(address);

        phonenumber.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        phonenumber.setForeground(new java.awt.Color(204, 204, 204));
        phonenumber.setText("Phone Number:");
        phonenumber.setBorder(null);
        phonenumber.setOpaque(false);
        phonenumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phonenumberMouseClicked(evt);
            }
        });
        jPanel2.add(phonenumber);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        city.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        city.setForeground(new java.awt.Color(204, 204, 204));
        city.setText("City:");
        city.setBorder(null);
        city.setOpaque(false);
        city.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cityMouseClicked(evt);
            }
        });
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        jPanel7.add(city);

        province.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        province.setForeground(new java.awt.Color(204, 204, 204));
        province.setText("Province:");
        province.setBorder(null);
        province.setOpaque(false);
        province.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                provinceMouseClicked(evt);
            }
        });
        province.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceActionPerformed(evt);
            }
        });
        jPanel7.add(province);

        jPanel2.add(jPanel7);

        signupbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/signupbutton1.png"))); // NOI18N
        signupbutton.setBorder(null);
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        personaloption.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(personaloption);
        personaloption.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        personaloption.setSelected(true);
        personaloption.setText("Personal");
        personaloption.setBorder(null);
        personaloption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personaloptionMouseClicked(evt);
            }
        });

        corporationoption.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(corporationoption);
        corporationoption.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        corporationoption.setForeground(new java.awt.Color(0, 0, 0));
        corporationoption.setText("Corporation");
        corporationoption.setBorder(null);
        corporationoption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                corporationoptionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(personaloption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                .addComponent(corporationoption)
                .addGap(73, 73, 73))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personaloption)
                    .addComponent(corporationoption))
                .addContainerGap())
        );

        backbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout signUpBackground1Layout = new javax.swing.GroupLayout(signUpBackground1);
        signUpBackground1.setLayout(signUpBackground1Layout);
        signUpBackground1Layout.setHorizontalGroup(
            signUpBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpBackground1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpBackground1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(signUpBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpBackground1Layout.createSequentialGroup()
                        .addComponent(signupbutton)
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpBackground1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))))
            .addGroup(signUpBackground1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signUpBackground1Layout.setVerticalGroup(
            signUpBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpBackground1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(signUpBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(signupbutton)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signUpBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signUpBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        // TODO add your handling code here:
        name.setText("");
        name.setForeground(Color.BLACK);
    }//GEN-LAST:event_nameMouseClicked

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
        username.setText("");
        username.setForeground(Color.BLACK);
    }//GEN-LAST:event_usernameMouseClicked

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
        email.setText("");
        email.setForeground(Color.BLACK);
    }//GEN-LAST:event_emailMouseClicked

    private void emailagainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailagainMouseClicked
        // TODO add your handling code here:
        emailagain.setText("");
        emailagain.setForeground(Color.BLACK);
    }//GEN-LAST:event_emailagainMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
        password.setText("");
        password.setForeground(Color.BLACK);
    }//GEN-LAST:event_passwordMouseClicked

    private void passwordagainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordagainMouseClicked
        // TODO add your handling code here:
        passwordagain.setText("");
        passwordagain.setForeground(Color.BLACK);
                    
            
    }//GEN-LAST:event_passwordagainMouseClicked

    private void addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressMouseClicked
        // TODO add your handling code here:
        address.setText("");
        address.setForeground(Color.BLACK);
    }//GEN-LAST:event_addressMouseClicked

    private void phonenumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phonenumberMouseClicked
        // TODO add your handling code here:
        phonenumber.setText("");
        phonenumber.setForeground(Color.BLACK);
    }//GEN-LAST:event_phonenumberMouseClicked

    private void duedateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duedateMouseClicked
        // TODO add your handling code here:
        duedate.setText("");
        duedate.setForeground(Color.BLACK);
    }//GEN-LAST:event_duedateMouseClicked

    private void cvcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvcMouseClicked
        // TODO add your handling code here:
        cvc.setText("");
        cvc.setForeground(Color.BLACK);
    }//GEN-LAST:event_cvcMouseClicked

    private void cardnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardnoMouseClicked
        // TODO add your handling code here:
        cardno.setText("");
        cardno.setForeground(Color.BLACK);
    }//GEN-LAST:event_cardnoMouseClicked

    private void cardnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardnameMouseClicked
        // TODO add your handling code here:
        cardname.setText("");
        cardname.setForeground(Color.BLACK);
    }//GEN-LAST:event_cardnameMouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void duedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duedateActionPerformed

    private void emailagainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailagainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailagainActionPerformed

    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
        // TODO add your handling code here:
        if ( !(password.getText()).equals(passwordagain.getText()) || !(email.getText()).equals(emailagain.getText()))
        {
            infoBox("There is something wrong. Please enter your information again.", "");
            
        }
        else
        {
            if(personaloption.isSelected()) {
            try {
            
                System.out.println(1);
            db.createPersonUser(cardno.getText(), duedate.getText(), parseInt(cvc.getText()), cardname.getText(),username.getText(),
            city.getText(), province.getText(),name.getText(), password.getText(), email.getText(), address.getText(), phonenumber.getText(), 
           picurl);
            
            
            
       
            
        } catch(Exception e) {
            e.getMessage();
        }
            }
            if (corporationoption.isSelected())   {
                System.out.println(2);
                    try {
                db.createCorporationUser(username.getText(),
            city.getText(), province.getText(),name.getText(), password.getText(), email.getText(), address.getText(), phonenumber.getText(), 
           picurl, cardno.getText());
                    } catch (Exception e) {
                        e.getMessage();
                    }
        }
            this.hide();
            new LoginScreen().setVisible(true);
        }
    }//GEN-LAST:event_signupbuttonActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void backbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbuttonMouseClicked
        // TODO add your handling code here:
        this.hide();
        LoginScreen login = new LoginScreen();
        login.setVisible(true);
    }//GEN-LAST:event_backbuttonMouseClicked

    private void corporationoptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_corporationoptionMouseClicked
        // TODO add your handling code here:
        cvc.setText("");
        cvc.setEnabled(false);
        duedate.setText("");
        duedate.setEnabled(false);
        cardname.setText("");
        cardname.setEnabled(false);
        cardno.setText("Special Thank Message:");
    }//GEN-LAST:event_corporationoptionMouseClicked

    private void personaloptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personaloptionMouseClicked
        // TODO add your handling code here:
        cvc.setText("CVC:");
        cvc.setEnabled(true);
        duedate.setText("Due Date:");
        duedate.setEnabled(true);
        cardname.setText("Name on the Card:");
        cardname.setEnabled(true);
        cardno.setText("Card No:");
    }//GEN-LAST:event_personaloptionMouseClicked

    private void browsefilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsefilebuttonActionPerformed
        // TODO add your handling code here:
        jFileChooser1.showOpenDialog(new UploadScreen());
        File file = jFileChooser1.getSelectedFile();
        String name = jFileChooser1.getName(jFileChooser1.getSelectedFile());
       System.out.println(name);
        BufferedImage img = null;
try {
    img = ImageIO.read(file);
} catch (IOException e) {
}
try {
    // retrieve image
     picurl = "build/classes/extonextgroup/extonext_v2/images/" + name;
    File outputfile = new File(picurl);
    ImageIO.write(img, "png", outputfile);
} catch (IOException e) {    
}
    }//GEN-LAST:event_browsefilebuttonActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void provinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinceActionPerformed

    private void cityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cityMouseClicked
        // TODO add your handling code here:
        city.setText("");
        city.setForeground(Color.BLACK);
    }//GEN-LAST:event_cityMouseClicked

    private void provinceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_provinceMouseClicked
        // TODO add your handling code here:
        province.setText("");
        province.setForeground(Color.BLACK);
    }//GEN-LAST:event_provinceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpForm().setVisible(true);
            }
        });
    }
    
    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "" + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel backbutton;
    private javax.swing.JButton browsefilebutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cardname;
    private javax.swing.JTextField cardno;
    private javax.swing.JTextField city;
    private javax.swing.JRadioButton corporationoption;
    private javax.swing.JTextField cvc;
    private javax.swing.JTextField duedate;
    private javax.swing.JTextField email;
    private javax.swing.JTextField emailagain;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JTextField passwordagain;
    private javax.swing.JRadioButton personaloption;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JTextField province;
    private netbeanscomponents.SignUpBackground signUpBackground1;
    private javax.swing.JButton signupbutton;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
