/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extonextgroup.extonext_v2;

import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.JFrame;
/**
 *
 * @author DELL
 */
public class MessagePage extends javax.swing.JFrame {

    /**
     * Creates new form MessagePage
     */
    public MessagePage() {
        initComponents();
    }
    
    
    
    
    ArrayList<String> m1;
    ArrayList<String> m2;
    ArrayList<String> m3;
    ArrayList<String> m4;
    public void paintPage() {
        // TODO add your handling code here:
        
        
        
        try{
            if(db.getReceivers(user).size() >=  1)
            { username2.setVisible(false);
              jButton2.setVisible(false);
              jButton3.setVisible(false);
              jButton4.setVisible(false);
              username3.setVisible(false);
              username4.setVisible(false);
              messages2.setVisible(false);
              messages3.setVisible(false);
              messages4.setVisible(false);
              sendbutton2.setVisible(false);
              sendbutton3.setVisible(false);
              sendbutton4.setVisible(false);        
              m1 = db.showMessages(user, username1.getText());
            username1.setText(db.getReceivers(user).get(0));
        String s = "";
        for(int i = 0; i < m1.size(); i = i + 3){
            s += m1.get(i) + ": " + m1.get(i + 2) + "\n";
        }
        messages1.setText(s);}
        }catch(Exception e){
            e.getMessage();
        }
        
        
        
        try{
            if(db.getReceivers(user).size() >=  2)
            { username2.setVisible(true);
              username3.setVisible(false);
              username4.setVisible(false);
              jButton2.setVisible(true);
              messages2.setVisible(true);
              messages3.setVisible(false);
              messages4.setVisible(false);
              sendbutton2.setVisible(true);
              sendbutton3.setVisible(false);
              sendbutton4.setVisible(false); 
                
                m2 = db.showMessages(user, username2.getText());
                username2.setText(db.getReceivers(user).get(1));
        String s2 = "";
        for(int i = 0; i < m2.size(); i = i + 3){
            s2 += m2.get(i) + ": " + m2.get(i + 2) + "\n";
        }
        messages2.setText(s2);
        }}catch(Exception e){
            e.getMessage();
        }
        
        try{
            if(db.getReceivers(user).size() >=  3){
              username3.setVisible(true);
              username4.setVisible(false);
              jButton3.setVisible(true);
              messages3.setVisible(true);
              messages4.setVisible(false);
              sendbutton3.setVisible(true);
              sendbutton4.setVisible(false);  
                
                
                m3 = db.showMessages(user, username3.getText());
                username3.setText(db.getReceivers(user).get(2));
        String s3 = "";
        for(int i = 0; i < m3.size(); i = i + 3){
            s3 += m3.get(i) + ": " + m3.get(i + 2) + "\n";
        }
        messages3.setText(s3);
        }}catch(Exception e){
            e.getMessage();
        }
         
        try{
            if(db.getReceivers(user).size() >=  4){
              username4.setVisible(true);          
              jButton4.setVisible(true);
              messages4.setVisible(true);
              sendbutton4.setVisible(true); 
                
                
                m4 = db.showMessages(user, username4.getText());
                username4.setText(db.getReceivers(user).get(3));
        String s4 = "";
        for(int i = 0; i < m4.size(); i = i + 3){
            s4 += m4.get(i) + ": " + m4.get(i + 2) + "\n";
        }
        messages4.setText(s4);
        }}catch(Exception e){
            e.getMessage();
        }
        
        
        
    }
DBConnector db = new DBConnector();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        profilemenu = new javax.swing.JMenuItem();
        logoutmenu = new javax.swing.JMenuItem();
        jOptionPane1 = new javax.swing.JOptionPane();
        messageBackground1 = new netbeanscomponents.MessageBackground();
        additembutton = new javax.swing.JButton();
        messagebutton = new javax.swing.JButton();
        profilebutton = new javax.swing.JButton();
        logobutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        messages1 = new javax.swing.JTextArea();
        sendbutton1 = new javax.swing.JButton();
        username1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        messages3 = new javax.swing.JTextArea();
        sendbutton3 = new javax.swing.JButton();
        username3 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        messages4 = new javax.swing.JTextArea();
        sendbutton4 = new javax.swing.JButton();
        username4 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        messages2 = new javax.swing.JTextArea();
        sendbutton2 = new javax.swing.JButton();
        username2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jPopupMenu1.setBackground(new java.awt.Color(204, 0, 255));
        jPopupMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jPopupMenu1.setAlignmentX(10.0F);

        profilemenu.setBackground(new java.awt.Color(204, 0, 255));
        profilemenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        profilemenu.setForeground(new java.awt.Color(255, 255, 255));
        profilemenu.setText("Go Profile");
        profilemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilemenuMouseClicked(evt);
            }
        });
        profilemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilemenuActionPerformed(evt);
            }
        });
        jPopupMenu1.add(profilemenu);

        logoutmenu.setBackground(new java.awt.Color(204, 0, 255));
        logoutmenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logoutmenu.setForeground(new java.awt.Color(255, 255, 255));
        logoutmenu.setText("Logout");
        logoutmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutmenuActionPerformed(evt);
            }
        });
        jPopupMenu1.add(logoutmenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        additembutton.setBackground(new java.awt.Color(255, 255, 255));
        additembutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/37x37uploadbutton.png"))); // NOI18N
        additembutton.setBorder(null);
        additembutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additembuttonActionPerformed(evt);
            }
        });

        messagebutton.setBackground(new java.awt.Color(255, 255, 255));
        messagebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/55x37messagebutton.png"))); // NOI18N
        messagebutton.setBorder(null);
        messagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagebuttonActionPerformed(evt);
            }
        });

        profilebutton.setBackground(new java.awt.Color(255, 255, 255));
        profilebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/37x37profilebutton.png"))); // NOI18N
        profilebutton.setBorder(null);
        profilebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebuttonActionPerformed(evt);
            }
        });

        logobutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/logo.png"))); // NOI18N
        logobutton.setBorder(null);
        logobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logobuttonActionPerformed(evt);
            }
        });

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/backbutton.png"))); // NOI18N
        backbutton.setBorder(null);
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        messages1.setColumns(20);
        messages1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        messages1.setRows(5);
        messages1.setText(" ");
        jScrollPane5.setViewportView(messages1);

        sendbutton1.setText("send");
        sendbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbutton1ActionPerformed(evt);
            }
        });

        username1.setText("jLabel2");

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));

        messages3.setColumns(20);
        messages3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        messages3.setRows(5);
        jScrollPane6.setViewportView(messages3);

        sendbutton3.setText("send");
        sendbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbutton3ActionPerformed(evt);
            }
        });

        username3.setText("jLabel2");

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));

        messages4.setColumns(20);
        messages4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        messages4.setRows(5);
        jScrollPane7.setViewportView(messages4);

        sendbutton4.setText("send");
        sendbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbutton4ActionPerformed(evt);
            }
        });

        username4.setText("jLabel2");

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 255));

        messages2.setEditable(false);
        messages2.setColumns(20);
        messages2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        messages2.setRows(5);
        jScrollPane8.setViewportView(messages2);

        sendbutton2.setText("send");
        sendbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbutton2ActionPerformed(evt);
            }
        });

        username2.setText("jLabel2");

        jButton1.setText("view text");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("view text");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("view text");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("view text");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout messageBackground1Layout = new javax.swing.GroupLayout(messageBackground1);
        messageBackground1.setLayout(messageBackground1Layout);
        messageBackground1Layout.setHorizontalGroup(
            messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageBackground1Layout.createSequentialGroup()
                .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messageBackground1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(messageBackground1Layout.createSequentialGroup()
                                .addComponent(username1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messageBackground1Layout.createSequentialGroup()
                                        .addComponent(sendbutton1)
                                        .addGap(17, 17, 17))
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(messageBackground1Layout.createSequentialGroup()
                                .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(messageBackground1Layout.createSequentialGroup()
                                        .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(52, 52, 52)
                                        .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, messageBackground1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(sendbutton3, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sendbutton2, javax.swing.GroupLayout.Alignment.LEADING)))))
                                    .addGroup(messageBackground1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(messageBackground1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(sendbutton4)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(messageBackground1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(logobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(526, 526, 526)
                        .addComponent(additembutton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messagebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        messageBackground1Layout.setVerticalGroup(
            messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageBackground1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(logobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(additembutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(messagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messageBackground1Layout.createSequentialGroup()
                        .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(messageBackground1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messageBackground1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendbutton1)
                                .addGap(28, 28, 28)))
                        .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(messageBackground1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendbutton2))
                            .addGroup(messageBackground1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(messageBackground1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(username1)
                        .addGap(109, 109, 109)
                        .addComponent(username2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messageBackground1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendbutton3))
                    .addGroup(messageBackground1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messageBackground1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messageBackground1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendbutton4))
                    .addGroup(messageBackground1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(messageBackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(messageBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(messageBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebuttonActionPerformed
        // TODO add your handling code here:
        jPopupMenu1.show(this,989,117);
    }//GEN-LAST:event_profilebuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.hide();
        openPage(previous);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void profilemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilemenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profilemenuMouseClicked

    private void profilemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilemenuActionPerformed
        // TODO add your handling code here:
        this.hide();
        try {
        if (db.personOrCorporation(user) == 1) {
       PersonalProfilePage personal = new PersonalProfilePage();
      
       personal.setPage(page);
       personal.setUser(user);
       personal.paintPage();
        personal.setVisible(true);
        }
        else {
            CorpProfilePage corp = new CorpProfilePage();
            
            corp.setPage(page);
            corp.setUser(user);
            corp.paintPage();
            corp.setVisible(true);
        }
        } catch (Exception e) {
            e.getMessage();        
        }
        

    }//GEN-LAST:event_profilemenuActionPerformed

    private void logoutmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutmenuActionPerformed
        // TODO add your handling code here:
        infoBox("Successfully logged out" , "logout" );
        this.hide();
        LoginScreen login = new LoginScreen();
        login.setVisible(true);
    }//GEN-LAST:event_logoutmenuActionPerformed

    private void logobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logobuttonActionPerformed
        // TODO add your handling code here:
        try {
        if ( db.personOrCorporation(user) == 1) {
        this.hide();
        MainPagePersonal personal = new MainPagePersonal();
        personal.setVisible(true);
        personal.setPage(page);
        personal.setUser(user);
        }
        else {
            this.hide();
        MainPageCorporation mainCor = new MainPageCorporation();
        mainCor.setVisible(true);
        mainCor.setPage(page);
        mainCor.setUser(user);
        }
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_logobuttonActionPerformed

    private void messagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagebuttonActionPerformed
        // TODO add your handling code here:
        this.hide();
        MessagePage message = new MessagePage();
        message.setPage(page);
        message.setUser(user);
        message.paintPage();
        message.setVisible(true);
    }//GEN-LAST:event_messagebuttonActionPerformed

    private void additembuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additembuttonActionPerformed
        // TODO add your handling code here:
        this.hide();
        UploadScreen upload = new UploadScreen();
        upload.setVisible(true);
        upload.setPage(page);
        upload.setUser(user);
    }//GEN-LAST:event_additembuttonActionPerformed

    private void sendbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbutton2ActionPerformed
        try{
        JFrame frame = new JFrame("Message");
        String name = JOptionPane.showInputDialog(frame, "Enter your message:");
        db.sendMessage(user, username2.getText(),name );
        ArrayList<String> m = db.showMessages(user, username2.getText());
        String s = "";
        for(int i = 0; i < m.size(); i = i + 3){
            s += m.get(i) + ": " + m.get(i + 2) + "\n";
        }
        messages2.setText(s);
        }catch(Exception e){
            e.getMessage();
        }
    }//GEN-LAST:event_sendbutton2ActionPerformed

    private void sendbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbutton1ActionPerformed
        try{
        JFrame frame = new JFrame("Message");
        String name = JOptionPane.showInputDialog(frame, "Enter your message:");
        db.sendMessage(user, username1.getText(),name );
        ArrayList<String> m = db.showMessages(user, username1.getText());
        String s = "";
        for(int i = 0; i < m.size(); i = i + 3){
            s += m.get(i) + ": " + m.get(i + 2) + "\n";
        }
        messages1.setText(s);
        }catch(Exception e){
            e.getMessage();
        }

    }//GEN-LAST:event_sendbutton1ActionPerformed

    private void sendbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbutton3ActionPerformed
        try{
        JFrame frame = new JFrame("Message");
        String name = JOptionPane.showInputDialog(frame, "Enter your message:");
        db.sendMessage(user, username3.getText(),name );
        ArrayList<String> m = db.showMessages(user, username3.getText());
        String s = "";
        for(int i = 0; i < m.size(); i = i + 3){
            s += m.get(i) + ": " + m.get(i + 2) + "\n";
        }
        messages3.setText(s);
        }catch(Exception e){
            e.getMessage();
        }
    }//GEN-LAST:event_sendbutton3ActionPerformed

    private void sendbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbutton4ActionPerformed
        try{
        JFrame frame = new JFrame("Message");
        String name = JOptionPane.showInputDialog(frame, "Enter your message:");
        db.sendMessage(user, username4.getText(),name );
        ArrayList<String> m = db.showMessages(user, username4.getText());
        String s = "";
        for(int i = 0; i < m.size(); i = i + 3){
            s += m.get(i) + ": " + m.get(i + 2) + "\n";
        }
        messages4.setText(s);
        }catch(Exception e){
            e.getMessage();
        }
    }//GEN-LAST:event_sendbutton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try{
         m2 = db.showMessages(user, username1.getText());
        String s2 = "";
        for(int i = 0; i < m2.size(); i = i + 3){
            s2 += m2.get(i) + ": " + m2.get(i + 2) + "\n";
        }
        messages1.setText(s2);
        }catch(Exception e){
            e.getMessage();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
         m2 = db.showMessages(user, username2.getText());
        String s2 = "";
        for(int i = 0; i < m2.size(); i = i + 3){
            s2 += m2.get(i) + ": " + m2.get(i + 2) + "\n";
        }
        messages2.setText(s2);
        }catch(Exception e){
            e.getMessage();
        }    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try{
         m2 = db.showMessages(user, username3.getText());
        String s2 = "";
        for(int i = 0; i < m2.size(); i = i + 3){
            s2 += m2.get(i) + ": " + m2.get(i + 2) + "\n";
        }
        messages3.setText(s2);
        }catch(Exception e){
            e.getMessage();
        }    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{
         m2 = db.showMessages(user, username4.getText());
        String s2 = "";
        for(int i = 0; i < m2.size(); i = i + 3){
            s2 += m2.get(i) + ": " + m2.get(i + 2) + "\n";
        }
        messages4.setText(s2);
        }catch(Exception e){
            e.getMessage();
        }    }//GEN-LAST:event_jButton4ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessagePage().setVisible(true);
            }
        });
    }
    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "" + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void setRecieverText(String a)
    {username1.setText(a);}
    
    public static String user;
    public static int page = 13;
    public static int previous;
    public static void setUser(String username){
        user = username;
    }
    public static void setPage(int pagenum){
        previous = pagenum;
    }
    
    public void openPage(int pagenum){
        if (previous == 1) {
            AddDonationListPage donaListPage = new AddDonationListPage();
            donaListPage.setVisible(true);
            donaListPage.setUser(user);
            
        }
        if (previous == 2) {
            AfterDonationPage donaPage = new AfterDonationPage();
            
            donaPage.setUser(user);
            donaPage.paintPage();
            donaPage.setVisible(true);
        }
        if (previous == 3) {
            AfterDonationScreenCorp donaScreenCorp = new AfterDonationScreenCorp();
            donaScreenCorp.setUser(user);
            donaScreenCorp.paintPage();
            donaScreenCorp.setVisible(true);
        }
        if (previous == 4) {
            BuyScreen buyScreen = new BuyScreen();
           
            buyScreen.setUser(user);
             buyScreen.setVisible(true);
        }
        if (previous == 5) {
            CorpDonateScreen corpScreen = new CorpDonateScreen();
            
            corpScreen.setUser(user);
            corpScreen.setVisible(true);
        }
        if (previous == 6) {
            CorpProfilePage corpProfile = new CorpProfilePage();
            
            corpProfile.setUser(user);
            corpProfile.paintPage();
            corpProfile.setVisible(true);
        }
        if (previous == 7) {
            DonationFilteredsearchCorp fiteredCorp = new DonationFilteredsearchCorp();
            
            fiteredCorp.setUser(user);
            fiteredCorp.paintPage();
            fiteredCorp.setVisible(true);
        }
        if (previous == 8) {
            FilteredBuyScreen filteredBuy = new FilteredBuyScreen();
            
            filteredBuy.setUser(user);
            filteredBuy.paintPage();
            filteredBuy.setVisible(true);
        }
        if (previous == 9) {
            ItemDetailsPage itemDetails = new ItemDetailsPage();
            
            itemDetails.setUser(user);
            itemDetails.paintPage();
            itemDetails.setVisible(true);
        }
        if (previous == 10) {
            
        }
        if (previous == 11) {
            MainPageCorporation mainCorporation = new MainPageCorporation();
            mainCorporation.setVisible(true);
            mainCorporation.setUser(user);
        }
        if (previous == 12) {
            MainPagePersonal mainPersonal = new MainPagePersonal();
            mainPersonal.setVisible(true);
            mainPersonal.setUser(user);
        }
        if (previous == 13) {
            MessagePage messagePage = new MessagePage();
            
            messagePage.setUser(user);
            messagePage.paintPage();
            messagePage.setVisible(true);
        }
        if (previous == 14) {
            PersonalProfilePage personProfile = new PersonalProfilePage();
            
            personProfile.setUser(user);
            personProfile.paintPage();
            personProfile.setVisible(true);
        }
        if (previous == 15) {
        }

        if (previous == 16) {
            UploadScreen upload = new UploadScreen();
            upload.setVisible(true);
            upload.setUser(user);
        }
        if (previous == 17) {
            WishListListPage wishListList = new WishListListPage();
            wishListList.setUser(user);
            wishListList.paintPage();
            wishListList.setVisible(true);
        }
        if (previous == 18) {
            WishListPageCorp wishList = new WishListPageCorp();
            
            wishList.setUser(user);
            wishList.paintPage();
            wishList.setVisible(true);
        }
        if (previous == 19) {
            WishListPagePersonal wishListPersonal = new WishListPagePersonal();
           
            wishListPersonal.setUser(user);
            wishListPersonal.paintPage();
             wishListPersonal.setVisible(true);
        }
        if (previous == 20) {
            DonationPersonalPage donationPersonal = new DonationPersonalPage();
            donationPersonal.setVisible(true);
            donationPersonal.setUser(user);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additembutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton logobutton;
    private javax.swing.JMenuItem logoutmenu;
    private netbeanscomponents.MessageBackground messageBackground1;
    private javax.swing.JButton messagebutton;
    private javax.swing.JTextArea messages1;
    private javax.swing.JTextArea messages2;
    private javax.swing.JTextArea messages3;
    private javax.swing.JTextArea messages4;
    private javax.swing.JButton profilebutton;
    private javax.swing.JMenuItem profilemenu;
    private javax.swing.JButton sendbutton1;
    private javax.swing.JButton sendbutton2;
    private javax.swing.JButton sendbutton3;
    private javax.swing.JButton sendbutton4;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    private javax.swing.JLabel username3;
    private javax.swing.JLabel username4;
    // End of variables declaration//GEN-END:variables
}
